### ISSUE TITLE
Parsing multiple measurements

### ISSUE THREAD

**Issue by RyanScottLewis** [mhuggins/ruby-measurement#5]
```
2.0.0-p247 :001 > %q{ 3' }.to_measurement
 => 3.0 ft.
2.0.0-p247 :002 > %q{ 2" }.to_measurement
 => 2.0 in.
2.0.0-p247 :003 > %q{ 3'2" }.to_measurement
ArgumentError: Invalid unit: ''2"'
  from /Users/ryguy/.rvm/gems/ruby-2.0.0-p247/gems/ruby-measurement-1.2.1/lib/ruby-measurement/measurement.rb:94:in `parse'
  from /Users/ryguy/.rvm/gems/ruby-2.0.0-p247/gems/ruby-measurement-1.2.1/lib/ruby-measurement/core_ext/string.rb:5:in `to_measurement'
  from (irb):18
  from /Users/ryguy/.rvm/rubies/ruby-2.0.0-p247/bin/irb:16:in `<main>'
2.0.0-p247 :004 > %q{ 3' }.to_measurement + %q{ 2" }.to_measurement
 => 3.1666666666666665 ft.
```

Line `:003` in the above output should also return `3.1666666666666665 ft.`

**Comment by RyanScottLewis** [comment]
Closing (stale)
